name: cargo
version: 0.0.1
author: Joris Hermans <hermansj@gmail.com>
description: A key value, storage library for dart
homepage: https://github.com/jorishermans/cargo
dependencies:
dev_dependencies:
  unittest: '>=0.9.0 <0.9.1'