name: cargo
version: 0.7.0
author: Joris Hermans <hermansj@gmail.com>
description: A 'key value' storage abstraction library for dart
homepage: https://github.com/ForceUniverse/cargo
dependencies:
  logging: '>=0.9.0 <0.10.0'
dev_dependencies:
  scheduled_test: ">=0.11.6 <0.12.0"