name: cargo
version: 0.8.0
author: Joris Hermans <hermansj@gmail.com>
description: A 'key value' storage abstraction library for dart
homepage: https://github.com/ForceUniverse/cargo
dependencies:
  logging: '>=0.10.0 <0.11.0'
dev_dependencies:
  scheduled_test: ">=0.11.6 <0.12.0"
environment:
  sdk: '>=1.9.0 <2.0.0'